# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_grafo', [dirname(__file__)])
        except ImportError:
            import _grafo
            return _grafo
        if fp is not None:
            try:
                _mod = imp.load_module('_grafo', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _grafo = swig_import_helper()
    del swig_import_helper
else:
    import _grafo
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Node(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Node, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Node, name)
    __repr__ = _swig_repr
    __swig_setmethods__["numero_nodos"] = _grafo.Node_numero_nodos_set
    __swig_getmethods__["numero_nodos"] = _grafo.Node_numero_nodos_get
    if _newclass:
        numero_nodos = _swig_property(_grafo.Node_numero_nodos_get, _grafo.Node_numero_nodos_set)
    __swig_setmethods__["numero_conexiones"] = _grafo.Node_numero_conexiones_set
    __swig_getmethods__["numero_conexiones"] = _grafo.Node_numero_conexiones_get
    if _newclass:
        numero_conexiones = _swig_property(_grafo.Node_numero_conexiones_get, _grafo.Node_numero_conexiones_set)

    def __init__(self):
        this = _grafo.new_Node()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def Add_path(self, arg2, arg3):
        return _grafo.Node_Add_path(self, arg2, arg3)

    def GetId(self):
        return _grafo.Node_GetId(self)

    def GetConexiones(self):
        return _grafo.Node_GetConexiones(self)

    def GetNumber_of_conections(self):
        return _grafo.Node_GetNumber_of_conections(self)
    __swig_destroy__ = _grafo.delete_Node
    __del__ = lambda self: None
Node_swigregister = _grafo.Node_swigregister
Node_swigregister(Node)
cvar = _grafo.cvar

class Grafo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Grafo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Grafo, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _grafo.new_Grafo(arg2)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def AddConexion(self, arg2, arg3, arg4):
        return _grafo.Grafo_AddConexion(self, arg2, arg3, arg4)

    def AddNodo(self):
        return _grafo.Grafo_AddNodo(self)

    def hay_arco(self, arg2, arg3):
        return _grafo.Grafo_hay_arco(self, arg2, arg3)

    def GetAdventureMap(self, arg2, arg3):
        return _grafo.Grafo_GetAdventureMap(self, arg2, arg3)

    def GetNodo(self, arg2):
        return _grafo.Grafo_GetNodo(self, arg2)

    def GetName(self):
        return _grafo.Grafo_GetName(self)

    def GetCantidad_nodos(self):
        return _grafo.Grafo_GetCantidad_nodos(self)
    __swig_destroy__ = _grafo.delete_Grafo
    __del__ = lambda self: None
Grafo_swigregister = _grafo.Grafo_swigregister
Grafo_swigregister(Grafo)

# This file is compatible with both classic and new-style classes.


